services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:Fyn52TsJsnXiV6TgRggtEtnH07mq/XKVa/umb+94U5g=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./backend/database:/var/www/html/database
    command: >
      sh -c "php artisan migrate --force &&
             php artisan config:cache &&
             php artisan route:cache &&
             php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    #working_dir: /app
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:8000/api
    depends_on:
      - backend
    command: >
      sh -c "npm run start"
