version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/var/www/html
    command: >
      sh -c "php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - APP_KEY=base64:mWHOrlMvpss91KlTv+g5VidMVMfq5dg9aWM4+BubfKo=
    depends_on:
      - frontend

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
